name: Dump ROM
 
on: push

env:
  URL: https://cfhcable.dl.sourceforge.net/project/wightroms//joyeuse/nitrogen/Nitrogen-OS-11-miatoll-20201010.zip


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
         
       - name: Initializing environments
         run: |
              sudo apt install wget 
              wget https://raw.githubusercontent.com/erfanoabdi/ErfanGSIs/master/setup.sh
              bash setup.sh
              rm setup.sh 
              
       - name: Download your rom
         run: |
              git clone -q --recurse-submodules https://github.com/erfanoabdi/Firmware_extractor extract 2>/dev/null
              echo "Downloading ROM .."
              cd extract
              mkdir input
              wget $URL -P input/ 2>/dev/null 
              echo "Download done !"
              
       - name: Dump ROM
         run: |
              cd extract
              ./extractor.sh input/*
              wget https://raw.githubusercontent.com/JamieHoSzeYui/ROM-Dumper/main/pack.sh
              sudo -s
              chmod -R 0777 *
              ./pack.sh out
              
       - name: cat download link
         run: cat extract/out/links.txt
              
